FROM python:latest

WORKDIR /opt/dask

# Dependances (Python)
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Source Code
COPY ./src .

# DASK Status Portal
EXPOSE 8787

# Entrypoint
ENTRYPOINT ["python", "main.py"]
